language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:6379:6379 redis:3
  - docker ps -a

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi